spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/wurdal}
    username: ${SPRING_DATASOURCE_USERNAME:wurdal}
    password: ${SPRING_DATASOURCE_PASSWORD:wurdal}
  flyway:
    enabled: true
    locations: classpath:db/migration
server:
  port: ${PORT:8080}
